// src/components/LanguageToggle.tsx
'use client'
import { useState, createContext, useContext, ReactNode, useEffect } from 'react'

type Language = 'he' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  he: {
    // Dashboard translations
    'trainer_dashboard': 'לוח בקרה למאמן',
    'set_availability': 'הגדרת זמינות',
    'view_clients': 'צפייה בלקוחות',
    'share_link': 'שיתוף קישור',
    'sign_out': 'התנתקות',
    'welcome_back_trainer': 'ברוכים השובים מאמן',
    'business_today': 'איך העסק שלכם היום?',
    'loading_dashboard': 'טוען לוח בקרה...',
    'refresh': 'רענון',
    'updating': 'מעדכן...',
    'todays_sessions': 'אימונים היום',
    'this_week': 'השבוע',
    'active_clients': 'לקוחות פעילים',
    'upcoming_sessions': 'אימונים קרובים',
    'scheduled': 'מתוזמנים',
    'quick_actions': 'פעולות מהירות',
    'manage_clients': 'ניהול לקוחות',
    'profile_info': 'פרטי פרופיל',
    'name': 'שם',
    'email': 'אימייל',
    'booking_url': 'כתובת הזמנות',
    'not_set': 'לא הוגדר',
    'no_upcoming_sessions': 'אין אימונים קרובים',
    'new_appointments_appear_here': 'הזמנות חדשות יופיעו כאן כשלקוחות יזמינו',
    'share_booking_link': 'שתף קישור הזמנות',
    'completed': 'הושלם',
    'scheduled_status': 'מתוזמן',
    'cancelled': 'בוטל',
    'privacy_policy': 'מדיניות פרטיות',
    'terms_of_service': 'תנאי שימוש',
    'login_for_trainers': 'התחברות למאמנים',
    'join_now': 'הצטרפו עכשיו',
    'want_to_register': 'רוצה להירשם',
    
    // Onboarding translations
    'welcome_to_system': 'ברוכים הבאים למערכת!',
    'lets_get_started': 'בואו נתחיל',
    'onboarding_intro': 'בכמה צעדים פשוטים תוכלו להתחיל לקבל הזמנות מלקוחות',
    'step': 'שלב',
    'set_your_availability': 'הגדירו את הזמינות שלכם',
    'set_availability_desc': 'הגדירו באילו ימים ושעות אתם זמינים לאימונים. המערכת תאפשר ללקוחות להזמין רק בזמנים אלו.',
    'test_calendar_connection': 'בדקו את החיבור ליומן',
    'test_calendar_desc': 'וודאו שהחיבור ליומן Google שלכם עובד כראוי. כל הזמנה תתווסף אוטומטית ליומן.',
    'share_your_link': 'שתפו את הקישור שלכם',
    'share_link_desc': 'שתפו את הקישור האישי שלכם עם לקוחות והם יוכלו להזמין אימונים ישירות.',
    'got_it': 'הבנתי!',
    'start_setup': 'התחל הגדרות',
    'skip_tutorial': 'דלג על ההדרכה',
    
    // Auth translations
    'signup': 'הרשמה',
    'create_account': 'יצירת חשבון',
    'already_have_account': 'כבר יש לך חשבון?',
    'dont_have_account': 'אין לך חשבון?',
    'full_name': 'שם מלא',
    'password': 'סיסמה',
    'confirm_password': 'אישור סיסמה',
    'or': 'או',
    'sign_in_with_email': 'התחבר עם אימייל',
    'sign_up_with_email': 'הירשם עם אימייל',
    'password_min_length': 'הסיסמה חייבת להכיל לפחות 8 תווים',
    'passwords_dont_match': 'הסיסמאות לא תואמות',
    'email_required': 'אימייל נדרש',
    'name_required': 'שם נדרש',
    'password_required': 'סיסמה נדרשת',
    'creating_account': 'יוצר חשבון...',
    'signing_in': 'מתחבר...',
    'account_created_successfully': 'החשבון נוצר בהצלחה!',
    'invalid_credentials': 'פרטי התחברות שגויים',
    'email_already_exists': 'משתמש עם אימייל זה כבר קיים',
    'email_password_required': 'אימייל וסיסמה נדרשים',
    'use_google_signin': 'אנא התחבר עם Google עבור חשבון זה',
    'redirecting': 'מפנה...',
    'professional_fitness': 'פלטפורמה מקצועית לניהול הזמנות אימונים',
    'sign_in_access': 'התחברו כדי לגשת ללוח הבקרה שלכם',
    'terms_service': 'תנאי השירות',
    'help_center': 'מרכז עזרה',
    'contact_us': 'צור קשר',
    'about': 'אודות',
    'personal_booking': 'קישור הזמנה אישי',
    'get_started': 'בואו נתחיל',
    'contact_form_description': 'השאירו פרטים ונחזור אליכם עם כל המידע על המערכת',
    'contact_success_message': 'תודה על פנייתכם! נחזור אליכם תוך 24 שעות.',
    'contact_error_message': 'אירעה שגיאה בשליחת הבקשה. אנא נסו שוב מאוחר יותר.',
    
    // Homepage translations
    'fitness_booking_system': 'מערכת הזמנות למאמני כושר',
    'simple_system_for_trainers': 'מערכת פשוטה לכושר ובריאות',
    'login': 'התחברות',
    'advanced_booking_system': 'מערכת הזמנות פשוטה',
    'for_fitness_trainers': 'לכושר ובריאות',
    'homepage_description': 'פלטפורמה מקצועית לניהול הזמנות עם חיבור ליומן Google ומעקב אחר לקוחות. הפכו את ניהול האימונים שלכם לפשוט ויעיל יותר מתמיד.',
    'why_choose_our_system': 'למה לבחור במערכת שלנו?',
    'everything_trainer_needs': 'כל מה שאתם צריכים לכושר ובריאות במקום אחד',
    'google_calendar_integration': 'חיבור ליומן Google',
    'google_calendar_description': 'סנכרון אוטומטי עם יומן Google שלכם. כל הזמנה חדשה תופיע מיד ביומן הפרטי שלכם עם כל הפרטים הרלוונטיים.',
    'personal_booking_link': 'קישור הזמנה אישי',
    'personal_link_description': 'כל מאמן מקבל קישור אישי ויוניק. שתפו אותו עם הלקוחות שלכם והם יוכלו להזמין פגישות ישירות ללא צורך ברישום.',
    'advanced_management': 'ניהול מתקדם',
    'advanced_management_description': 'לוח בקרה מקצועי עם מעקב אחר כל ההזמנות, פרטי לקוחות, וניהול זמינות. הכל במקום אחד ונגיש.',
    'sms_reminders': 'תזכורות SMS',
    'sms_reminders_description': 'שלחו תזכורות SMS אוטומטיות ללקוחות שלכם לפני האימונים. הפחיתו ביטולים ושפרו את חווית הלקוח.',
    'coming_soon': 'בקרוב',
    'mobile_app': 'אפליקציית מובייל',
    'mobile_app_description': 'אפליקציה ייעודית למאמנים וללקוחות עם התראות push, גישה אופליין ותיעוד מהיר של אימונים.',
    'payment_integration': 'מערכת תשלומים',
    'payment_integration_description': 'קבלת תשלומים מובנית, חיוב אוטומטי, ניהול מנויים וחבילות, ודוחות פיננסיים מפורטים.',
    
    // Analytics translations
    'appointment_growth': 'צמיחת האימונים',
    'last_8_weeks': '8 השבועות האחרונים',
    'loading_analytics': 'טוען נתוני אנליטיקה...',
    'average_per_week': 'ממוצע שבועי',
    'total_8_weeks': 'סה"כ 8 שבועות',
    'previous_weeks': 'שבועות קודמים',
    'current_week': 'השבוע הנוכחי',
    'no_analytics_data': 'אין נתוני אנליטיקה',
    'analytics_data_will_appear': 'נתוני צמיחה יופיעו כאן לאחר קיום אימונים',
    
    // Footer translations
    'footer_description': 'מערכת ניהול מתקדמת למאמני כושר. הפכו את ניהול האימונים שלכם לפשוט ויעיל יותר מתמיד.',
    'quick_links': 'קישורים מהירים',
    'booking_page': 'עמוד הזמנות',
    'legal': 'משפטי',
    'terms_of_service': 'תנאי שימוש',
    'privacy_policy': 'מדיניות פרטיות',
    'contact_support': 'תמיכה',
    'all_rights_reserved': 'כל הזכויות שמורות.',
    'developed_by': 'פותח על ידי',
    'copy': 'העתק',
    'phone': 'טלפון',
    'registered_trainers': 'מאמנים רשומים',
    'workouts_completed': 'אימונים בוצעו',
    'satisfaction_rate': 'שביעות רצון',
    'start_today': 'התחילו עוד היום!',
    'join_many_trainers': 'הצטרפו למאמנים רבים שכבר משתמשים במערכת ומנהלים את העסק שלהם ביעילות מקסימלית',
    'join_now_free': 'הצטרפו עכשיו - בחינם',
    'copyright_2024': '© 2024 FitnessPro. כל הזכויות שמורות.',
    
    // Testimonial translations
    'what_trainers_say': 'מה המאמנים אומרים',
    'testimonial_text': 'המערכת הזו שינתה לי את החיים! הלקוחות שלי יכולים להזמין אימונים ישירות דרך הקישור, הכל מתעדכן באלקטרוניקה שלי, וזה חוסך לי שעות של תיאום. הכי פשוט ויעיל שיש!',
    'testimonial_name': 'ירון הוכמן',
    'testimonial_title': 'מאמן כושר, MVMNT Factory עכו',
    
    // Login page translations
    'continue_google': 'המשך עם Google',
    'secure_login': 'התחברות מאובטחת',
    'what_youll_get': 'מה תקבלו',
    'calendar_integration': 'סנכרון יומן אוטומטי',
    'client_management': 'ניהול לקוחות מתקדם',
    'session_tracking': 'מעקב אחר אימונים',
    'trainer_login': 'התחברות מאמנים',
    'welcome_back': 'ברוכים השובים',
    'sign_in_continue': 'התחברו כדי להמשיך',
    'google_calendar_sync': 'סנכרון עם יומן Google',
    'manage_appointments': 'ניהול הזמנות',
    'track_clients': 'מעקב אחר לקוחות',
    'easy_scheduling': 'תזמון קל ופשוט',
    'professional_dashboard': 'לוח בקרה מקצועי',
    'instant_notifications': 'התראות מיידיות',
    'secure_data': 'נתונים מאובטחים',
    'mobile_friendly': 'ידידותי לנייד',
    'quick_setup': 'הגדרה מהירה',
    'already_registered': 'כבר רשומים? נהדר!',
    'new_here': 'חדשים כאן?',
    'get_started': 'בואו נתחיל',
    'loading': 'טוען...',
    'error': 'שגיאה',
    'try_again': 'נסו שוב',
    'contact_support': 'צרו קשר עם התמיכה',
    
    // Booking page translations
    'book_session_with': 'הזמן אימון עם',
    'select_date_time': 'בחר תאריך ושעה המתאימים לך',
    'booking_appointment': 'הזמנת אימון',
    'select_time_start_training': 'בחר את הזמן המתאים לך ונתחיל להתאמן יחד!',
    'click_desired_date_time': 'לחץ על התאריך והשעה הרצויים',
    'date': 'תאריך',
    'available_times': 'שעות זמינות',
    'loading_available_times': 'טוען שעות זמינות...',
    'no_available_times': 'אין שעות זמינות בתאריך זה',
    'booking_details': 'פרטי ההזמנה',
    'fill_details_complete': 'מלא את הפרטים כדי להשלים את ההזמנה',
    'session_summary': 'סיכום הפגישה',
    'time': 'שעה',
    'trainer': 'מאמן',
    'full_name': 'שם מלא',
    'your_name': 'השם שלך',
    'email_address': 'כתובת אימייל',
    'phone_number': 'מספר טלפון',
    'phone_placeholder': '050-1234567',
    'sending_booking': 'שולח הזמנה...',
    'book_session': 'הזמן אימון',
    'booking_success': 'הזמנה נשלחה בהצלחה!',
    'booking_success_message': 'ההזמנה שלך ל-',
    'at_time': 'בשעה',
    'sent_to_trainer': 'נשלחה למאמן',
    'confirmation_email': 'תקבל אישור בקרוב למייל',
    'booking_error': 'שגיאה ביצירת הזמנה',
    
    // Client Profile translations
    'loading_client_profile': 'טוען פרופיל לקוח...',
    'client_not_found': 'לקוח לא נמצא',
    'back_to_client_list': 'חזרה לרשימת לקוחות',
    'back_to_clients': 'חזרה ללקוחות',
    'clients': 'לקוחות',
    'record_payment': 'רישום תשלום',
    'outstanding_balance': 'יתרה לתשלום',
    'payment_history': 'היסטוריית תשלומים',
    'payments_recorded': 'תשלומים רשומים',
    'basic_information': 'מידע בסיסי',
    'session_history_upcoming': 'היסטוריית אימונים ופגישות עתידיות',
    'total_appointments': 'סך הכל פגישות',
    'cancel': 'ביטול',
    'recording': 'רושם...',
    'record_payment_btn': 'רשום תשלום',
    'book_session_btn': 'הזמן אימון',
    'saving': 'שומר...',
    'save_changes': 'שמור שינויים',
    'edit_profile': 'ערוך פרופיל',
    'cancelling': 'מבטל...',
    'deleting': 'מוחק...',
    'delete': 'מחק',
    'amount_ils': 'סכום (₪)',
    'enter_payment_amount': 'הזן סכום תשלום',
    'payment_method': 'אמצעי תשלום',
    'cash': 'מזומן',
    'bank_transfer': 'העברה בנקאית',
    'credit_card': 'כרטיס אשראי',
    'paypal': 'PayPal',
    'check': 'צ\'ק',
    'notes_optional': 'הערות (אופציונלי)',
    'payment_notes': 'הערות לתשלום...',
    'phone_placeholder': '050-1234567',
    'client_info_saved': 'מידע הלקוח נשמר בהצלחה!',
    'error_saving_info': 'שגיאה בשמירת המידע',
    'enter_valid_payment': 'אנא הזן סכום תשלום תקף',
    'payment_recorded_success': 'התשלום נרשם בהצלחה!',
    'error_recording_payment': 'שגיאה ברישום התשלום',
    'cancel_appointment_confirm': 'האם אתה בטוח שברצונך לבטל את הפגישה? פעולה זו תסיר אותה גם מהיומן שלך.',
    'appointment_cancelled': 'הפגישה בוטלה בהצלחה!',
    'error_cancelling_appointment': 'שגיאה בביטול הפגישה',
    'appointment_booked_success': '✓ הפגישה נקבעה בהצלחה! אישור נשלח ל',
    'client_since': 'לקוח מתאריך',
    'fully_paid': '✅ שולם במלואו!',
    'total_sessions': 'סך הכל אימונים',
    'total_owed': 'סך הכל לתשלום',
    'total_paid': 'סך הכל שולם',
    'outstanding': 'יתרה',
    'not_provided': 'לא סופק',
    'upcoming_sessions': 'אימונים עתידיים',
    'session_history': 'היסטוריית אימונים',
    'minutes': 'דקות',
    'notes': 'הערות',
    'showing_last_sessions': 'מציג את 10 האימונים האחרונים •',
    'more_sessions_history': 'אימונים נוספים בהיסטוריה',
    'no_appointments_yet': 'אין פגישות עדיין',
    'book_first_session': 'הזמן את האימון הראשון עם לקוח זה כדי לראות את היסטוריית הפגישות כאן.',
    'per_hour': 'לשעה',
    'owed': 'חוב',
    'client_notes': 'הערות לקוח',
    'nutrition_plan': 'תוכנית תזונה',
    'edit_notes': 'ערוך הערות',
    'edit_nutrition_plan': 'ערוך תוכנית תזונה',
    'notes_placeholder': 'הוסף הערות על הלקוח...',
    'nutrition_plan_placeholder': 'הוסף פרטי תוכנית תזונה...',
    'no_notes_added': 'לא נוספו הערות עדיין',
    'no_nutrition_plan': 'לא נוספה תוכנית תזונה עדיין',
    'click_to_add_notes': 'לחץ על ערוך הערות כדי להוסיף מידע על הלקוח הזה',
    'click_to_add_nutrition_plan': 'לחץ על ערוך תוכנית תזונה כדי להוסיף הנחיות תזונתיות ותוכניות ארוחות',
    'progress_tracking': 'מעקב התקדמות',
    'add_measurement': 'הוסף מדידה',
    'weight': 'משקל',
    'body_measurements': 'מדידות גוף',
    'chest': 'חזה',
    'waist': 'מותניים',
    'hips': 'ירכיים',
    'arms': 'זרועות',
    'thighs': 'ירכיים',
    'date': 'תאריך',
    'measurement_date': 'תאריך מדידה',
    'weight_kg': 'משקל (ק"ג)',
    'chest_cm': 'חזה (ס"מ)',
    'waist_cm': 'מותניים (ס"מ)',
    'hips_cm': 'ירכיים (ס"מ)',
    'arms_cm': 'זרועות (ס"מ)',
    'thighs_cm': 'ירכיים (ס"מ)',
    'add_new_measurement': 'הוסף מדידה חדשה',
    'save_measurement': 'שמור מדידה',
    'no_measurements_yet': 'אין מדידות רשומות עדיין',
    'start_tracking_progress': 'התחל לעקוב אחר התקדמות על ידי הוספת המדידה הראשונה',
    'view_charts': 'הצג גרפים',
    'view_table': 'הצג טבלה',
    'measurement_history': 'היסטוריית מדידות',
    'delete_measurement': 'מחק מדידה',
    'confirm_delete_measurement': 'האם אתה בטוח שברצונך למחוק את המדידה הזו?',
    'weight_progress': 'התקדמות במשקל',
    'measurements_progress': 'התקדמות במדידות',
    'latest': 'אחרון',
    'change': 'שינוי',
    'bmi': 'BMI',
    'body_fat_percentage': 'אחוז שומן',
    'notes_optional': 'הערות (אופציונלי)',
    
    // Clients Overview translations
    'client_management': 'ניהול לקוחות',
    'dashboard': 'לוח בקרה',
    'back_to_dashboard': 'חזרה ללוח בקרה',
    'your_clients': 'הלקוחות שלך 👥',
    'client_directory': 'מדריך לקוחות',
    'schedule_session': 'תזמון אימון',
    'set_availability': 'הגדרת זמינות',
    'share_booking_link': 'שתף קישור הזמנה',
    'search_clients': 'חפש לקוחות לפי שם או אימייל...',
    'active': 'פעיל',
    'existing': 'קיים',
    'new': 'חדש',
    'loading_clients': 'טוען לקוחות...',
    'no_clients_found': 'לא נמצאו לקוחות',
    'no_clients_yet': 'אין לקוחות עדיין',
    'no_clients_match_search': 'אין לקוחות תואמים ל"{searchTerm}". נסה מונח חיפוש אחר.',
    'clients_added_automatically': 'לקוחות יתווספו אוטומטית כשהם יזמינו אימונים',
    'clients_count': 'לקוחות',
    'total_clients': 'סך הכל לקוחות',
    'active_this_month': 'פעילים החודש',
    'total_sessions': 'סך הכל אימונים',
    'total': 'סך הכל',
    'done': 'בוצע',
    'upcoming': 'עתידיים',
    'manage_client_relationships': 'נהל את הקשרים עם הלקוחות ועקוב אחר הפרוגרס שלהם',
    'find_manage_clients': 'מצא ונהל את הלקוחות שלך',
    'joined': 'הצטרף',
    'last': 'אחרון:',
    'goals': 'מטרות:',
    'scheduling_feature_coming_soon': 'תכונת תזמון תזמין בקרוב! לעת עתה, תוכל להגדיר את הזמינות שלך ולשתף את קישור ההזמנה עם הלקוחות.'
  },
  en: {
    // Dashboard translations
    'trainer_dashboard': 'Trainer Dashboard',
    'set_availability': 'Set Availability',
    'view_clients': 'View Clients',
    'share_link': 'Share Link',
    'sign_out': 'Sign Out',
    'welcome_back_trainer': 'Welcome Back Trainer',
    'business_today': 'How\'s your business today?',
    'loading_dashboard': 'Loading dashboard...',
    'refresh': 'Refresh',
    'updating': 'Updating...',
    'todays_sessions': 'Today\'s Sessions',
    'this_week': 'This Week',
    'active_clients': 'Active Clients',
    'upcoming_sessions': 'Upcoming Sessions',
    'scheduled': 'scheduled',
    'quick_actions': 'Quick Actions',
    'manage_clients': 'Manage Clients',
    'profile_info': 'Profile Info',
    'name': 'Name',
    'email': 'Email',
    'booking_url': 'Booking URL',
    'not_set': 'Not set',
    'no_upcoming_sessions': 'No upcoming sessions',
    'new_appointments_appear_here': 'New appointments will appear here when clients book',
    'share_booking_link': 'Share booking link',
    'completed': 'Completed',
    'scheduled_status': 'Scheduled',
    'cancelled': 'Cancelled',
    'privacy_policy': 'Privacy Policy',
    'terms_of_service': 'Terms of Service',
    'login_for_trainers': 'Login for Trainers',
    'join_now': 'Join Now',
    'want_to_register': 'Want to Register',
    
    // Onboarding translations
    'welcome_to_system': 'Welcome to the System!',
    'lets_get_started': 'Let\'s Get Started',
    'onboarding_intro': 'In a few simple steps, you\'ll be ready to receive bookings from clients',
    'step': 'Step',
    'set_your_availability': 'Set Your Availability',
    'set_availability_desc': 'Define which days and hours you\'re available for training. The system will only allow clients to book during these times.',
    'test_calendar_connection': 'Test Calendar Connection',
    'test_calendar_desc': 'Make sure your Google Calendar connection is working properly. Every booking will be automatically added to your calendar.',
    'share_your_link': 'Share Your Link',
    'share_link_desc': 'Share your personal link with clients and they can book sessions directly.',
    'got_it': 'Got it!',
    'start_setup': 'Start Setup',
    'skip_tutorial': 'Skip Tutorial',
    
    // Auth translations
    'signup': 'Sign Up',
    'create_account': 'Create Account',
    'already_have_account': 'Already have an account?',
    'dont_have_account': 'Don\'t have an account?',
    'full_name': 'Full Name',
    'password': 'Password',
    'confirm_password': 'Confirm Password',
    'or': 'OR',
    'sign_in_with_email': 'Sign in with Email',
    'sign_up_with_email': 'Sign up with Email',
    'password_min_length': 'Password must be at least 8 characters',
    'passwords_dont_match': 'Passwords don\'t match',
    'email_required': 'Email is required',
    'name_required': 'Name is required',
    'password_required': 'Password is required',
    'creating_account': 'Creating account...',
    'signing_in': 'Signing in...',
    'account_created_successfully': 'Account created successfully!',
    'invalid_credentials': 'Invalid credentials',
    'email_already_exists': 'User with this email already exists',
    'email_password_required': 'Email and password are required',
    'use_google_signin': 'Please sign in with Google for this account',
    'redirecting': 'Redirecting...',
    'professional_fitness': 'Professional platform for managing training appointments',
    'sign_in_access': 'Sign in to access your dashboard',
    'terms_service': 'Terms of Service',
    'help_center': 'Help Center',
    'contact_us': 'Contact Us',
    'about': 'About',
    'personal_booking': 'Personal Booking Link',
    'get_started': 'Get Started',
    'contact_form_description': 'Leave your details and we\'ll get back to you with all the information about the system',
    'contact_success_message': 'Thank you for your inquiry! We\'ll get back to you within 24 hours.',
    'contact_error_message': 'An error occurred while submitting the request. Please try again later.',
    
    // Homepage translations
    'fitness_booking_system': 'Fitness Trainer Booking System',
    'simple_system_for_trainers': 'Simple System for Fitness and Wellbeing',
    'login': 'Login',
    'advanced_booking_system': 'Simple Booking System',
    'for_fitness_trainers': 'For Fitness and Wellbeing',
    'homepage_description': 'Professional platform for managing appointments with Google Calendar integration and client tracking. Make your training management simpler and more efficient than ever.',
    'why_choose_our_system': 'Why Choose Our System?',
    'everything_trainer_needs': 'Everything you need for fitness and wellbeing in one place',
    'google_calendar_integration': 'Google Calendar Integration',
    'google_calendar_description': 'Automatic sync with your Google Calendar. Every new appointment appears instantly in your personal calendar with all relevant details.',
    'personal_booking_link': 'Personal Booking Link',
    'personal_link_description': 'Each trainer gets a unique personal link. Share it with your clients and they can book sessions directly without needing to register.',
    'advanced_management': 'Advanced Management',
    'advanced_management_description': 'Professional dashboard with tracking of all appointments, client details, and availability management. Everything in one accessible place.',
    'sms_reminders': 'SMS Reminders',
    'sms_reminders_description': 'Send automatic SMS reminders to your clients before training sessions. Reduce cancellations and improve customer experience.',
    'coming_soon': 'Coming Soon',
    'mobile_app': 'Mobile App',
    'mobile_app_description': 'Dedicated app for trainers and clients with push notifications, offline access, and quick session tracking.',
    'payment_integration': 'Payment Integration',
    'payment_integration_description': 'Built-in payment processing, automatic billing, subscription management, and detailed financial reports.',
    
    // Analytics translations
    'appointment_growth': 'Appointment Growth',
    'last_8_weeks': 'Last 8 Weeks',
    'loading_analytics': 'Loading analytics...',
    'average_per_week': 'Weekly Average',
    'total_8_weeks': 'Total 8 Weeks',
    'previous_weeks': 'Previous Weeks',
    'current_week': 'Current Week',
    'no_analytics_data': 'No Analytics Data',
    'analytics_data_will_appear': 'Growth data will appear here after conducting sessions',
    
    // Footer translations
    'footer_description': 'Advanced management system for fitness trainers. Make managing your workouts simpler and more efficient than ever.',
    'quick_links': 'Quick Links',
    'booking_page': 'Booking Page',
    'legal': 'Legal',
    'terms_of_service': 'Terms of Service',
    'privacy_policy': 'Privacy Policy',
    'contact_support': 'Contact Support',
    'all_rights_reserved': 'All rights reserved.',
    'developed_by': 'Developed by',
    'copy': 'Copy',
    'phone': 'Phone',
    'registered_trainers': 'Registered Trainers',
    'workouts_completed': 'Workouts Completed',
    'satisfaction_rate': 'Satisfaction Rate',
    'start_today': 'Start Today!',
    'join_many_trainers': 'Join many trainers who are already using the system and managing their business with maximum efficiency',
    'join_now_free': 'Join Now - Free',
    'copyright_2024': '© 2024 FitnessPro. All rights reserved.',
    
    // Testimonial translations
    'what_trainers_say': 'What Trainers Say',
    'testimonial_text': 'This system has been a game-changer for my business! My clients can book sessions directly through my link, everything syncs with my calendar automatically, and it saves me hours of coordination. It\'s simply the best and most efficient solution out there!',
    'testimonial_name': 'Yaron Hochman',
    'testimonial_title': 'Fitness Trainer, MVMNT Factory Akko',
    
    // Login page translations
    'continue_google': 'Continue with Google',
    'secure_login': 'Secure Login',
    'what_youll_get': 'What You\'ll Get',
    'calendar_integration': 'Automatic Calendar Sync',
    'client_management': 'Advanced Client Management',
    'session_tracking': 'Session Tracking',
    'trainer_login': 'Trainer Login',
    'welcome_back': 'Welcome Back',
    'sign_in_continue': 'Sign in to continue',
    'google_calendar_sync': 'Google Calendar Sync',
    'manage_appointments': 'Manage Appointments',
    'track_clients': 'Track Clients',
    'easy_scheduling': 'Easy Scheduling',
    'professional_dashboard': 'Professional Dashboard',
    'instant_notifications': 'Instant Notifications',
    'secure_data': 'Secure Data',
    'mobile_friendly': 'Mobile Friendly',
    'quick_setup': 'Quick Setup',
    'already_registered': 'Already registered? Great!',
    'new_here': 'New here?',
    'get_started': 'Let\'s get started',
    'loading': 'Loading...',
    'error': 'Error',
    'try_again': 'Try again',
    'contact_support': 'Contact support',
    
    // Booking page translations
    'book_session_with': 'Book Session with',
    'select_date_time': 'Select a date and time that works for you',
    'booking_appointment': 'Booking Appointment',
    'select_time_start_training': 'Choose the time that suits you and let\'s start training together!',
    'click_desired_date_time': 'Click on your desired date and time',
    'date': 'Date',
    'available_times': 'Available Times',
    'loading_available_times': 'Loading available times...',
    'no_available_times': 'No available times on this date',
    'booking_details': 'Booking Details',
    'fill_details_complete': 'Fill in the details to complete your booking',
    'session_summary': 'Session Summary',
    'time': 'Time',
    'trainer': 'Trainer',
    'full_name': 'Full Name',
    'your_name': 'Your name',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'phone_placeholder': '555-123-4567',
    'sending_booking': 'Sending booking...',
    'book_session': 'Book Session',
    'booking_success': 'Booking sent successfully!',
    'booking_success_message': 'Your booking for',
    'at_time': 'at',
    'sent_to_trainer': 'has been sent to the trainer',
    'confirmation_email': 'You will receive confirmation soon at',
    'booking_error': 'Error creating booking',
    
    // Client Profile translations
    'loading_client_profile': 'Loading client profile...',
    'client_not_found': 'Client not found',
    'back_to_client_list': 'Back to Client List',
    'back_to_clients': 'Back to Clients',
    'clients': 'Clients',
    'record_payment': 'Record Payment',
    'outstanding_balance': 'Outstanding balance',
    'payment_history': 'Payment History',
    'payments_recorded': 'payments recorded',
    'basic_information': 'Basic Information',
    'session_history_upcoming': 'Session History & Upcoming Appointments',
    'total_appointments': 'total appointments',
    'cancel': 'Cancel',
    'recording': 'Recording...',
    'record_payment_btn': 'Record Payment',
    'book_session_btn': 'Book Session',
    'saving': 'Saving...',
    'save_changes': 'Save Changes',
    'edit_profile': 'Edit Profile',
    'cancelling': 'Cancelling...',
    'deleting': 'Deleting...',
    'delete': 'Delete',
    'amount_ils': 'Amount (₪)',
    'enter_payment_amount': 'Enter payment amount',
    'payment_method': 'Payment Method',
    'cash': 'Cash',
    'bank_transfer': 'Bank Transfer',
    'credit_card': 'Credit Card',
    'paypal': 'PayPal',
    'check': 'Check',
    'notes_optional': 'Notes (optional)',
    'payment_notes': 'Payment notes...',
    'phone_placeholder': '555-123-4567',
    'client_info_saved': 'Client information saved successfully!',
    'error_saving_info': 'Error saving information',
    'enter_valid_payment': 'Please enter a valid payment amount',
    'payment_recorded_success': 'Payment recorded successfully!',
    'error_recording_payment': 'Error recording payment',
    'cancel_appointment_confirm': 'Are you sure you want to cancel this appointment? This will also remove it from your calendar.',
    'appointment_cancelled': 'Appointment cancelled successfully!',
    'error_cancelling_appointment': 'Error cancelling appointment',
    'appointment_booked_success': '✓ Appointment booked successfully! Confirmation email sent to',
    'client_since': 'Client since',
    'fully_paid': '✅ Fully paid up!',
    'total_sessions': 'Total Sessions',
    'total_owed': 'Total Owed',
    'total_paid': 'Total Paid',
    'outstanding': 'Outstanding',
    'not_provided': 'Not provided',
    'upcoming_sessions': 'Upcoming Sessions',
    'session_history': 'Session History',
    'minutes': 'minutes',
    'notes': 'Notes',
    'showing_last_sessions': 'Showing last 10 sessions •',
    'more_sessions_history': 'more sessions in history',
    'no_appointments_yet': 'No appointments yet',
    'book_first_session': 'Book the first session with this client to see appointment history here.',
    'per_hour': 'per hour',
    'owed': 'owed',
    'client_notes': 'Client Notes',
    'nutrition_plan': 'Nutrition Plan',
    'edit_notes': 'Edit Notes',
    'edit_nutrition_plan': 'Edit Nutrition Plan',
    'notes_placeholder': 'Add notes about the client...',
    'nutrition_plan_placeholder': 'Add nutrition plan details...',
    'no_notes_added': 'No notes added yet',
    'no_nutrition_plan': 'No nutrition plan added yet',
    'click_to_add_notes': 'Click Edit Notes to add information about this client',
    'click_to_add_nutrition_plan': 'Click Edit Nutrition Plan to add dietary guidelines and meal plans',
    'progress_tracking': 'Progress Tracking',
    'add_measurement': 'Add Measurement',
    'weight': 'Weight',
    'body_measurements': 'Body Measurements',
    'chest': 'Chest',
    'waist': 'Waist',
    'hips': 'Hips',
    'arms': 'Arms',
    'thighs': 'Thighs',
    'date': 'Date',
    'measurement_date': 'Measurement Date',
    'weight_kg': 'Weight (kg)',
    'chest_cm': 'Chest (cm)',
    'waist_cm': 'Waist (cm)',
    'hips_cm': 'Hips (cm)',
    'arms_cm': 'Arms (cm)',
    'thighs_cm': 'Thighs (cm)',
    'add_new_measurement': 'Add New Measurement',
    'save_measurement': 'Save Measurement',
    'no_measurements_yet': 'No measurements recorded yet',
    'start_tracking_progress': 'Start tracking progress by adding the first measurement',
    'view_charts': 'View Charts',
    'view_table': 'View Table',
    'measurement_history': 'Measurement History',
    'delete_measurement': 'Delete Measurement',
    'confirm_delete_measurement': 'Are you sure you want to delete this measurement?',
    'weight_progress': 'Weight Progress',
    'measurements_progress': 'Measurements Progress',
    'latest': 'Latest',
    'change': 'Change',
    'bmi': 'BMI',
    'body_fat_percentage': 'Body Fat %',
    'notes_optional': 'Notes (optional)',
    
    // Clients Overview translations
    'client_management': 'Client Management',
    'dashboard': 'Dashboard',
    'back_to_dashboard': 'Back to Dashboard',
    'your_clients': 'Your Clients 👥',
    'client_directory': 'Client Directory',
    'schedule_session': 'Schedule Session',
    'set_availability': 'Set Availability',
    'share_booking_link': 'Share Booking Link',
    'search_clients': 'Search clients by name or email...',
    'active': 'Active',
    'existing': 'Existing',
    'new': 'New',
    'loading_clients': 'Loading clients...',
    'no_clients_found': 'No clients found',
    'no_clients_yet': 'No clients yet',
    'no_clients_match_search': 'No clients match "{searchTerm}". Try a different search term.',
    'clients_added_automatically': 'Clients will be automatically added when they book sessions',
    'clients_count': 'clients',
    'total_clients': 'Total Clients',
    'active_this_month': 'Active This Month',
    'total_sessions': 'Total Sessions',
    'total': 'Total',
    'done': 'Done',
    'upcoming': 'Upcoming',
    'manage_client_relationships': 'Manage your client relationships and track their progress',
    'find_manage_clients': 'Find and manage your clients',
    'joined': 'Joined',
    'last': 'Last:',
    'goals': 'Goals:',
    'scheduling_feature_coming_soon': 'Scheduling feature coming soon! For now, you can set your availability and share your booking link with clients.'
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('he')
  const [isClient, setIsClient] = useState(false)

  useEffect(() => {
    setIsClient(true)
    // Load language from localStorage on client side
    const savedLanguage = localStorage.getItem('language') as Language
    if (savedLanguage && (savedLanguage === 'he' || savedLanguage === 'en')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', lang)
    }
  }

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]]
    if (!translation) {
      console.warn(`Missing translation for key: ${key} in language: ${language}`)
      return key
    }
    return translation
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useTranslations() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useTranslations must be used within a LanguageProvider')
  }
  return context
}

export default function LanguageToggle() {
  const { language, setLanguage } = useTranslations()

  const handleToggle = () => {
    const newLang = language === 'he' ? 'en' : 'he'
    setLanguage(newLang)
  }

  return (
    <button
      onClick={handleToggle}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '6px',
        padding: '8px 12px',
        fontSize: '13px',
        fontWeight: '500',
        color: '#374151',
        backgroundColor: '#f3f4f6',
        border: 'none',
        borderRadius: '6px',
        cursor: 'pointer',
        transition: 'all 0.2s'
      }}
      onMouseOver={(e) => e.currentTarget.style.backgroundColor = '#e5e7eb'}
      onMouseOut={(e) => e.currentTarget.style.backgroundColor = '#f3f4f6'}
    >
      <svg width="14" height="14" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5h12M9 3v2m1.048 9.5A18.022 18.022 0 016.412 9m6.088 9h7M11 21l5-10 5 10M12.751 5C11.783 10.77 8.07 15.61 3 18.129" />
      </svg>
      {language === 'he' ? 'EN' : 'עב'}
    </button>
  )
}